# Generated by Django 2.0.5 on 2018-05-09 07:23

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geocontext', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contextcache',
            name='geometry_linestring_3d',
            field=django.contrib.gis.db.models.fields.LineStringField(blank=True, dim=3, help_text='The 3d line geometry of the context.', null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='contextcache',
            name='geometry_multi_linestring_3d',
            field=django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, dim=3, help_text='The 3d multi line geometry of the context.', null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='contextcache',
            name='geometry_multi_polygon_3d',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, dim=3, help_text='The 3d multi polygon geometry of the context.', null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='contextcache',
            name='geometry_polygon_3d',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, dim=3, help_text='The 3d polygon geometry of the context.', null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='contextcache',
            name='geometry_linestring',
            field=django.contrib.gis.db.models.fields.LineStringField(blank=True, help_text='The line geometry of the context.', null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='contextcache',
            name='geometry_multi_linestring',
            field=django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, help_text='The multi line geometry of the context.', null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='contextcache',
            name='geometry_multi_polygon',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, help_text='The multi polygon geometry of the context.', null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='contextcache',
            name='geometry_polygon',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, help_text='The polygon geometry of the context.', null=True, srid=4326),
        ),
    ]
