# Generated by Django 3.1.8 on 2021-09-15 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocontext', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='layer_geometry_field',
            field=models.CharField(blank=True, help_text='Geometry field of the sercive if needed.', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='cache_duration',
            field=models.IntegerField(blank=True, default=604800, help_text='Service refresh time in seconds - determines Cache persistence. Default is one week.', null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='layer_name',
            field=models.CharField(help_text='Required name of the actual layer/feature to retrieve (Property name). Geocontext v1 used "Result regex"', max_length=200),
        ),
        migrations.AlterField(
            model_name='service',
            name='layer_typename',
            field=models.CharField(blank=True, help_text='Layer type name to get from the service (WMS/WFS).', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='tolerance',
            field=models.FloatField(blank=True, default=10, help_text='Tolerance around query point in meters. Used for bounding box queries. Also determines cache hit range for all values', null=True),
        ),
    ]
