# Generated by Django 2.0.6 on 2018-06-27 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geocontext', '0003_contextserviceregistry_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, verbose_name='Order')),
            ],
        ),
        migrations.CreateModel(
            name='ContextCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Key of context collection.', max_length=200, unique=True)),
                ('name', models.CharField(help_text='Display Name of Context Collection.', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ContextGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Key of context group.', max_length=200, unique=True)),
                ('name', models.CharField(help_text='Display Name of Context Service.', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ContextGroupServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, verbose_name='Order')),
                ('context_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geocontext.ContextGroup')),
                ('context_service_registry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geocontext.ContextServiceRegistry')),
            ],
        ),
        migrations.AddField(
            model_name='collectiongroups',
            name='context_collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geocontext.ContextCollection'),
        ),
        migrations.AddField(
            model_name='collectiongroups',
            name='context_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geocontext.ContextGroup'),
        ),
    ]
