# Generated by Django 3.1.14 on 2022-02-14 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocontext', '0003_userprofile_usertier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertier',
            name='request_limit',
            field=models.CharField(default='100/day', help_text='API request limit for user. Enter "-" for unlimited requests', max_length=100),
        ),
    ]
