# Generated by Django 3.1.14 on 2022-07-28 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geocontext', '0003_userprofile_usertier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertier',
            name='request_limit',
            field=models.CharField(default='100/day', help_text='API request limit for user. Enter "-" for unlimited requests', max_length=100),
        ),
        migrations.CreateModel(
            name='OfferTier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, default='')),
                ('quantity', models.IntegerField(default=0, verbose_name='The quantity of the offer')),
                ('user_tier', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='geocontext.usertier')),
            ],
        ),
    ]
