# Generated by Django 3.1.14 on 2022-04-24 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geocontext', '0004_auto_20220214_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferTier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, default='')),
                ('quantity', models.IntegerField(default=0, verbose_name='The quantity of the offer')),
                ('user_tier', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='geocontext.usertier')),
            ],
        ),
    ]
