# Generated by Django 2.0.6 on 2018-06-27 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocontext', '0006_auto_20180627_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='contextcollection',
            name='context_groups',
            field=models.ManyToManyField(blank=True, help_text='List of context group in this context collection.', through='geocontext.CollectionGroups', to='geocontext.ContextGroup'),
        ),
        migrations.AddField(
            model_name='contextcollection',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the Context Collection.', null=True),
        ),
        migrations.AddField(
            model_name='contextgroup',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the Context Group.', null=True),
        ),
        migrations.AlterField(
            model_name='collectiongroups',
            name='order',
            field=models.IntegerField(blank=True, default=0, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='contextgroup',
            name='context_service_registries',
            field=models.ManyToManyField(blank=True, help_text='List of context service registry in the context group.', through='geocontext.ContextGroupServices', to='geocontext.ContextServiceRegistry'),
        ),
    ]
