# Generated by Django 2.0.6 on 2018-06-27 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geocontext', '0007_auto_20180627_1003'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='collectiongroups',
            unique_together={('context_collection', 'context_group')},
        ),
        migrations.AlterUniqueTogether(
            name='contextgroupservices',
            unique_together={('context_group', 'context_service_registry')},
        ),
    ]
