# Generated by Django 2.0.6 on 2018-06-27 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocontext', '0008_auto_20180627_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectiongroups',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='contextgroupservices',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Order'),
        ),
    ]
