# Generated by Django 2.0.6 on 2018-06-27 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocontext', '0009_auto_20180627_1030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contextserviceregistry',
            name='display_name',
        ),
        migrations.AddField(
            model_name='contextserviceregistry',
            name='name',
            field=models.CharField(default='', help_text='Name of Context Service.', max_length=200),
            preserve_default=False,
        ),
    ]
