# Generated by Django 2.0.7 on 2018-07-10 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocontext', '0011_remove_contextserviceregistry_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contextcache',
            name='source_uri',
            field=models.CharField(blank=True, help_text='Source URI of the Context.', max_length=1000, null=True),
        ),
    ]
