# Generated by Django 2.0.7 on 2018-07-15 03:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocontext', '0012_auto_20180710_0342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contextcollection',
            name='key',
            field=models.CharField(help_text='Key of context collection.', max_length=200, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_key', message='Key must only contains lower case or underscore.', regex='^[0-9a-z_]+$')]),
        ),
        migrations.AlterField(
            model_name='contextgroup',
            name='key',
            field=models.CharField(help_text='Key of context group.', max_length=200, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_key', message='Key must only contains lower case or underscore.', regex='^[0-9a-z_]+$')]),
        ),
        migrations.AlterField(
            model_name='contextserviceregistry',
            name='key',
            field=models.CharField(help_text='Key of Context Service.', max_length=200, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_key', message='Key must only contains lower case or underscore.', regex='^[0-9a-z_]+$')]),
        ),
    ]
