# Generated by Django 2.0.7 on 2018-07-17 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocontext', '0014_auto_20180716_0624'),
    ]

    operations = [
        migrations.AddField(
            model_name='contextserviceregistry',
            name='licensing',
            field=models.CharField(blank=True, help_text='The licensing scheme for the Context Service Registry.', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='contextserviceregistry',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes for the Context Service Registry.', null=True),
        ),
        migrations.AddField(
            model_name='contextserviceregistry',
            name='provenance',
            field=models.CharField(blank=True, help_text='The origin or source of the Context Service Registry.', max_length=1000, null=True),
        ),
    ]
