# Generated by Django 2.0.7 on 2018-08-02 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocontext', '0015_auto_20180717_0333'),
    ]

    operations = [
        migrations.AddField(
            model_name='contextgroup',
            name='group_type',
            field=models.CharField(choices=[('text', 'Text'), ('graph', 'Graph')], default='text', help_text='Type of the group to determine the UI.', max_length=10),
        ),
    ]
