# Generated by Django 2.1.3 on 2018-11-22 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocontext', '0017_auto_20181121_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='contextserviceregistry',
            name='is_graphable',
            field=models.BooleanField(blank=True, help_text='The licensing scheme for the Context Service Registry.', null=True),
        ),
    ]
