# Generated by Django 2.1.3 on 2018-11-22 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocontext', '0018_contextserviceregistry_is_graphable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contextserviceregistry',
            name='is_graphable',
        ),
        migrations.AddField(
            model_name='contextserviceregistry',
            name='is_graph',
            field=models.BooleanField(blank=True, help_text='Indicates if this registry returns data from which a graph can be drawn.', null=True),
        ),
    ]
