# Generated by Django 2.1.3 on 2018-11-22 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocontext', '0019_auto_20181122_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contextserviceregistry',
            name='is_graph',
            field=models.BooleanField(blank=True, default=False, help_text='Indicates if this registry returns data from which a graph can be drawn.'),
            preserve_default=False,
        ),
    ]
