# Generated by Django 2.1.3 on 2018-11-23 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocontext', '0020_auto_20181122_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contextserviceregistry',
            name='is_graph',
        ),
        migrations.AddField(
            model_name='contextgroup',
            name='is_graph',
            field=models.BooleanField(blank=True, default=False, help_text='Indicates if this registry returns data from which a graph can be drawn.'),
        ),
    ]
