# Generated by Django 2.1.3 on 2018-11-27 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocontext', '0022_auto_20181126_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contextserviceregistry',
            name='query_type',
            field=models.CharField(choices=[('WFS', 'WFS'), ('WCS', 'WCS'), ('WMS', 'WMS'), ('REST', 'REST'), ('ArcREST', 'ArcREST'), ('Wikipedia', 'Wikipedia'), ('PlaceName', 'PlaceName')], help_text='Query type of the Context Service.', max_length=200),
        ),
    ]
