# Generated by Django 2.1.7 on 2019-03-26 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocontext', '0023_auto_20181127_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contextserviceregistry',
            name='api_key',
            field=models.CharField(blank=True, help_text='API key for accessing Context Service. For PlaceName queries this is your username.', max_length=200, null=True),
        ),
    ]
