# Generated by Django 3.0.5 on 2020-05-03 14:37

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geocontext', '0024_auto_20190326_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='contextcache',
            name='geometry_point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='The point geometry of the query.', null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='contextcache',
            name='geometry_point_3d',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, dim=3, help_text='The 3d point geometry of the query.', null=True, srid=4326),
        ),
    ]
