# Generated by Django 3.0.6 on 2020-06-01 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocontext', '0026_auto_20200531_1222'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ['key']},
        ),
        migrations.AlterModelOptions(
            name='csr',
            options={'ordering': ['key']},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['key']},
        ),
        migrations.AddField(
            model_name='csr',
            name='resolution',
            field=models.IntegerField(blank=True, help_text='Fundamental resolution of the source data in m.', null=True),
        ),
    ]
