# Generated by Django 3.0.6 on 2020-06-02 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocontext', '0027_auto_20200601_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csr',
            name='resolution',
            field=models.IntegerField(blank=True, help_text='Base data resolution of the source data in meter.', null=True),
        ),
    ]
