# Generated by Django 3.0.7 on 2020-06-06 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocontext', '0027_auto_20200601_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='csr',
            name='buffer_dist',
            field=models.FloatField(blank=True, help_text='Search distance around query point in meters. Helpful for non-polygon features. Also determines cache hit range for rasters', null=True),
        ),
    ]
