# Generated by Django 3.0.7 on 2020-06-06 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocontext', '0028_auto_20200602_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='csr',
            name='search_dist',
            field=models.FloatField(blank=True, help_text='Distance to search for feature around query point in meter. Helpful for linear features', null=True),
        ),
        migrations.AlterField(
            model_name='csr',
            name='resolution',
            field=models.FloatField(blank=True, help_text='Base data resolution of the source data in meter.', null=True),
        ),
    ]
