version: '3.9'
volumes:
  nginx-conf-volume:
    driver_opts:
      type: none
      device: ${PWD}/sites-enabled
      o: bind
  static-volume:
    driver_opts:
      type: none
      device: ${PWD}/static
      o: bind
  media-volume:
    driver_opts:
      type: none
      device: ${PWD}/media
      o: bind
  reports-volume:
    driver_opts:
      type: none
      device: ${PWD}/reports
      o: bind
  db-backup-volume:
    driver_opts:
      type: none
      device: ${PWD}/backups
      o: bind
  db-sql-volume:
    driver_opts:
      type: none
      device: ${PWD}/sql
      o: bind

x-common-dev:
  &default-common-django-dev
  image: geocontext-devweb
  build:
    context: ./docker
    dockerfile: Dockerfile-slim-dev
  environment:
    - REDIS_HOST=${REDIS_HOST:-redis}
    - REDIS_PASSWORD=${REDIS_PASSWORD:-redis_password}
    - DATABASE_NAME=gis
    - DATABASE_USERNAME=docker
    - DATABASE_PASSWORD=docker
    - DATABASE_HOST=db
    - DJANGO_SETTINGS_MODULE=core.settings.prod_docker
    - PYTHONPATH=/usr/src/geocontext
    - VIRTUAL_HOST=geocontext.kartoza.com
    - VIRTUAL_PORT=8080
  volumes:
    - ../django_project:/usr/src/geocontext
    - static-volume:/home/web/static:rw
    - media-volume:/home/web/media:rw
    - reports-volume:/home/web/reports
    - ./logs:/var/log/
  links:
    - db:db

services:
  devweb:
    <<: *default-common-django-dev
    links:
      - db:db
      - worker:worker
    ports:
      - "${HTTP_DEBUG_PORT}:8080"

  worker:
    <<: *default-common-django-dev
    entrypoint: []
    command: 'celery -A geocontext worker -l info'
    links:
      - db
      - redis

  db:
    ports:
      - "${POSTGRES_PORT}:5432"
