FROM python:3.8-slim-buster

LABEL maintainer="Andre Theron<andre.theron@kartoza.com>"

RUN DEBIAN_FRONTEND=noninteractive \
    && apt-get update -y \
    && apt-get install -y --no-install-recommends \
    binutils \
    gcc \
    gdal-bin \
    git \
    libproj-dev \
    libgdal-dev \
    python3-gdal \
    python3-geoip \
    python3-setuptools \
    && rm -rf /var/lib/apt/lists/*

ADD requirements.txt /etc/geocontext/requirements.txt
RUN pip3 install --upgrade pip setuptools
RUN pip3 install --no-cache-dir -r /etc/geocontext/requirements.txt

ADD requirements-dev.txt /etc/geocontext/requirements-dev.txt
RUN pip install -r /etc/geocontext/requirements-dev.txt
ADD bashrc /root/.bashrc

# Open port 8080 as we will be running our django dev server on
EXPOSE 8080
# Open port 22 as we will be using a remote interpreter from pycharm
EXPOSE 22

CMD ["tail", "-f", "/dev/null"]
