apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --out k8s
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: dbbackups
  name: dbbackups
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: dbbackups
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --out k8s
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: dbbackups
    spec:
      containers:
      - env:
        - name: DUMPPREFIX
          value: PG_geocontext
        - name: POSTGRES_DBNAME
          value: gis
        - name: POSTGRES_HOST
          value: db
        - name: POSTGRES_PASS
          value: docker
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_USER
          value: docker
        image: kartoza/pg-backup:12.0
        imagePullPolicy: ""
        name: geocontext-db-backups
        resources: {}
        volumeMounts:
        - mountPath: /backups
          name: db-backup-volume
      hostname: pg-backups
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: db-backup-volume
        persistentVolumeClaim:
          claimName: db-backup-volume-db-0
status: {}
