apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --out k8s
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: uwsgi
  name: uwsgi
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: uwsgi
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --out k8s
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: uwsgi
    spec:
      containers:
      - env:
        - name: DATABASE_HOST
          value: db
        - name: DATABASE_NAME
          value: gis
        - name: DATABASE_PASSWORD
          value: docker
        - name: DATABASE_USERNAME
          value: docker
        - name: DJANGO_SETTINGS_MODULE
          value: core.settings.prod_docker
        - name: PYTHONPATH
          value: /usr/src/geocontext
        - name: VIRTUAL_HOST
          value: geocontext.kartoza.com
        - name: VIRTUAL_PORT
          value: "8080"
        image: kartoza/geocontext:2.0
        imagePullPolicy: Always
        name: geocontext-uwsgi
        resources: {}
        command:
          - /etc/geocontext/entry-point.sh
        args:
          - uwsgi
          - --ini /etc/geocontext/uwsgi.conf
        volumeMounts:
        - mountPath: /home/web/static
          name: static-volume
        - mountPath: /home/web/media
          name: media-volume
        - mountPath: /home/web/reports
          name: reports-volume
        - mountPath: /etc/geocontext/entry-point.sh
          name: geocontext-config
          subPath: entry-point.sh
      hostname: uwsgi
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: geocontext-config
        configMap:
          name: geocontext-config
          defaultMode: 0755
      - name: static-volume
        persistentVolumeClaim:
          claimName: static-volume
      - name: media-volume
        persistentVolumeClaim:
          claimName: media-volume
      - name: reports-volume
        persistentVolumeClaim:
          claimName: reports-volume
status: {}
